export const mockStories = [
  {
    id: '1',
    title: 'The Crystal Nexus',
    summary: 'A mystical adventure through enchanted realms where ancient crystals hold the power to reshape reality itself.',
    coverImage: 'https://images.pexels.com/photos/1054218/pexels-photo-1054218.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=1',
    creator: {
      id: '1',
      username: 'EtherScribe',
      avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
    },
    collaborators: [
      {
        id: '2',
        username: 'MysticTales',
        avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
      },
      {
        id: '3',
        username: 'ChronicleKeeper',
        avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
      },
    ],
    genre: 'fantasy',
    status: 'active',
    createdAt: '2024-01-10T10:30:00Z',
    stats: {
      totalReaders: 1247,
      totalVotes: 892,
      averageRating: 4.6,
    },
    tags: ['magic', 'adventure', 'mystery', 'crystals'],
  },
  {
    id: '2',
    title: 'Neon Shadows',
    summary: 'In a cyberpunk metropolis, a rogue hacker discovers a conspiracy that threatens the very fabric of digital reality.',
    coverImage: 'https://images.pexels.com/photos/2159549/pexels-photo-2159549.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=1',
    creator: {
      id: '4',
      username: 'CyberNarrativa',
      avatar: 'https://images.pexels.com/photos/1680172/pexels-photo-1680172.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
    },
    collaborators: [
      {
        id: '5',
        username: 'DigitalDreamer',
        avatar: 'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
      },
    ],
    genre: 'sci-fi',
    status: 'active',
    createdAt: '2024-01-08T14:22:00Z',
    stats: {
      totalReaders: 934,
      totalVotes: 721,
      averageRating: 4.3,
    },
    tags: ['cyberpunk', 'hacking', 'conspiracy', 'technology'],
  },
  {
    id: '3',
    title: 'The Last Lighthouse',
    summary: 'On a remote island, the keeper of the last functioning lighthouse must choose between duty and survival.',
    coverImage: 'https://images.pexels.com/photos/417074/pexels-photo-417074.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=1',
    creator: {
      id: '6',
      username: 'SeaStoryteller',
      avatar: 'https://images.pexels.com/photos/1065084/pexels-photo-1065084.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
    },
    collaborators: [
      {
        id: '7',
        username: 'OceanMystic',
        avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
      },
      {
        id: '8',
        username: 'StormWeaver',
        avatar: 'https://images.pexels.com/photos/1310522/pexels-photo-1310522.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
      },
    ],
    genre: 'drama',
    status: 'active',
    createdAt: '2024-01-12T09:15:00Z',
    stats: {
      totalReaders: 687,
      totalVotes: 445,
      averageRating: 4.8,
    },
    tags: ['lighthouse', 'isolation', 'duty', 'survival'],
  },
  {
    id: '4',
    title: 'Quantum Hearts',
    summary: 'A love story that spans multiple dimensions, where two souls keep finding each other across infinite realities.',
    coverImage: 'https://images.pexels.com/photos/1624496/pexels-photo-1624496.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=1',
    creator: {
      id: '9',
      username: 'DimensionalRomance',
      avatar: 'https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
    },
    collaborators: [],
    genre: 'romance',
    status: 'completed',
    createdAt: '2023-12-20T16:40:00Z',
    stats: {
      totalReaders: 2103,
      totalVotes: 1567,
      averageRating: 4.9,
    },
    tags: ['multiverse', 'romance', 'quantum', 'destiny'],
  },
  {
    id: '5',
    title: 'The Memory Thief',
    summary: 'In a world where memories can be stolen and sold, a detective must solve crimes using fragments of forgotten thoughts.',
    coverImage: 'https://images.pexels.com/photos/1629236/pexels-photo-1629236.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=1',
    creator: {
      id: '10',
      username: 'MindBender',
      avatar: 'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
    },
    collaborators: [
      {
        id: '11',
        username: 'ThoughtWeaver',
        avatar: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
      },
    ],
    genre: 'mystery',
    status: 'active',
    createdAt: '2024-01-05T11:20:00Z',
    stats: {
      totalReaders: 1089,
      totalVotes: 823,
      averageRating: 4.5,
    },
    tags: ['memory', 'detective', 'noir', 'mind'],
  },
  {
    id: '6',
    title: 'The Clockwork Rebellion',
    summary: 'In a steampunk world, mechanical beings gain consciousness and fight for their freedom against their human creators.',
    coverImage: 'https://images.pexels.com/photos/159298/gears-cogs-machine-machinery-159298.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=1',
    creator: {
      id: '12',
      username: 'SteamCrafter',
      avatar: 'https://images.pexels.com/photos/1040881/pexels-photo-1040881.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
    },
    collaborators: [],
    genre: 'steampunk',
    status: 'pending',
    createdAt: '2024-01-15T08:30:00Z',
    stats: {
      totalReaders: 756,
      totalVotes: 432,
      averageRating: 4.4,
    },
    tags: ['steampunk', 'rebellion', 'consciousness', 'freedom'],
  },
  {
    id: '7',
    title: 'Echoes of Tomorrow',
    summary: 'A time traveler discovers that changing the past creates dangerous ripples that threaten to unravel reality itself.',
    coverImage: 'https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=1',
    creator: {
      id: '13',
      username: 'TimeWeaver',
      avatar: 'https://images.pexels.com/photos/1484794/pexels-photo-1484794.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
    },
    collaborators: [
      {
        id: '14',
        username: 'ChronoScribe',
        avatar: 'https://images.pexels.com/photos/1212984/pexels-photo-1212984.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
      },
    ],
    genre: 'sci-fi',
    status: 'active',
    createdAt: '2024-01-18T12:45:00Z',
    stats: {
      totalReaders: 1234,
      totalVotes: 987,
      averageRating: 4.7,
    },
    tags: ['time-travel', 'paradox', 'reality', 'consequences'],
  },
  {
    id: '8',
    title: 'The Whispering Woods',
    summary: 'Ancient trees hold the memories of a forgotten civilization, and only a young botanist can unlock their secrets.',
    coverImage: 'https://images.pexels.com/photos/1563356/pexels-photo-1563356.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=1',
    creator: {
      id: '15',
      username: 'ForestKeeper',
      avatar: 'https://images.pexels.com/photos/1065084/pexels-photo-1065084.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
    },
    collaborators: [],
    genre: 'fantasy',
    status: 'active',
    createdAt: '2024-01-20T16:20:00Z',
    stats: {
      totalReaders: 892,
      totalVotes: 654,
      averageRating: 4.6,
    },
    tags: ['nature', 'ancient', 'secrets', 'botany'],
  },
];

export const mockProposals = [
  {
    id: 'p1',
    title: 'The Starforge Academy',
    summary: 'Young cadets at an interstellar military academy discover that their training simulations are actually real battles affecting distant worlds.',
    coverImage: 'https://images.pexels.com/photos/586063/pexels-photo-586063.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=1',
    creator: {
      id: '12',
      username: 'SpaceAcademy',
      avatar: 'https://images.pexels.com/photos/1040881/pexels-photo-1040881.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
    },
    genre: 'sci-fi',
    status: 'pending',
    createdAt: '2024-01-15T08:30:00Z',
    votes: { yes: 87, no: 23 },
    firstChapter: {
      title: 'Arrival at Starforge',
      content: 'The transport shuttle shuddered as it broke through the academy\'s atmosphere shield. Cadet Elena Martinez pressed her face to the viewport, watching the massive structure grow larger. Starforge Academy wasn\'t just a school—it was a small city floating in space, its crystalline spires catching the light of three suns.',
      choices: [
        { id: 'c1', text: 'Elena heads straight to her assigned dormitory to meet her roommate' },
        { id: 'c2', text: 'Elena explores the academy\'s central hub to get oriented' },
        { id: 'c3', text: 'Elena seeks out the simulation chambers she\'s heard so much about' },
      ],
    },
    votingDeadline: '2024-02-15T23:59:59Z',
    tags: ['space', 'academy', 'military', 'simulation'],
  },
  {
    id: 'p2',
    title: 'The Clockwork Garden',
    summary: 'In a steampunk Victorian London, a brilliant inventor creates mechanical flowers that begin to exhibit signs of consciousness.',
    coverImage: 'https://images.pexels.com/photos/132634/pexels-photo-132634.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=1',
    creator: {
      id: '13',
      username: 'BrassGears',
      avatar: 'https://images.pexels.com/photos/1484794/pexels-photo-1484794.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
    },
    genre: 'steampunk',
    status: 'active',
    createdAt: '2024-01-14T15:45:00Z',
    votes: { yes: 156, no: 34 },
    firstChapter: {
      title: 'The Workshop of Wonders',
      content: 'Steam hissed from the pipes that snaked across the ceiling of Professor Eliza Blackthorne\'s workshop. Gears clicked and whirred as her latest creation—a rose made entirely of brass and copper—slowly unfurled its metallic petals. But something was different about this one. As she watched, the flower turned toward her, as if sensing her presence.',
      choices: [
        { id: 'c1', text: 'Eliza carefully examines the flower\'s mechanical components' },
        { id: 'c2', text: 'Eliza tries to communicate with the flower' },
        { id: 'c3', text: 'Eliza quickly documents her observations in her journal' },
      ],
    },
    votingDeadline: '2024-02-10T23:59:59Z',
    tags: ['steampunk', 'inventor', 'consciousness', 'Victorian'],
  },
  {
    id: 'p3',
    title: 'The Dream Merchant',
    summary: 'A mysterious trader sells bottled dreams to insomniacs, but when nightmares start leaking into reality, the consequences become deadly.',
    coverImage: 'https://images.pexels.com/photos/1261728/pexels-photo-1261728.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=1',
    creator: {
      id: '14',
      username: 'NightWeaver',
      avatar: 'https://images.pexels.com/photos/1212984/pexels-photo-1212984.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
    },
    genre: 'horror',
    status: 'active',
    createdAt: '2024-01-13T20:12:00Z',
    votes: { yes: 203, no: 67 },
    firstChapter: {
      title: 'The Night Market',
      content: 'The alley behind Morpheus Street existed only between midnight and 3 AM. Sarah Chen clutched the crumpled business card as she navigated the shadows, looking for the vendor who promised to cure her three-month bout of insomnia. The Dream Merchant\'s stall appeared like a mirage—shelves lined with glowing bottles, each containing swirling, ethereal mist.',
      choices: [
        { id: 'c1', text: 'Sarah asks about the different types of dreams available' },
        { id: 'c2', text: 'Sarah inquires about the price and payment methods' },
        { id: 'c3', text: 'Sarah questions the safety of bottled dreams' },
      ],
    },
    votingDeadline: '2024-02-08T23:59:59Z',
    tags: ['dreams', 'merchant', 'horror', 'nightmares'],
  },
  {
    id: 'p4',
    title: 'The Digital Afterlife',
    summary: 'When consciousness can be uploaded to the cloud, a programmer discovers that the digital afterlife has its own dark secrets.',
    coverImage: 'https://images.pexels.com/photos/2582937/pexels-photo-2582937.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=1',
    creator: {
      id: '16',
      username: 'CodeMystic',
      avatar: 'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
    },
    genre: 'sci-fi',
    status: 'active',
    createdAt: '2024-01-22T10:15:00Z',
    votes: { yes: 124, no: 45 },
    firstChapter: {
      title: 'Upload Complete',
      content: 'The notification blinked green on Marcus\'s screen: "Consciousness Transfer: 100% Complete." His grandmother\'s body lay still in the hospital bed, but her digital avatar smiled at him from the monitor. "Hello, dear," she said, her voice perfectly replicated. But something in her eyes seemed... different.',
      choices: [
        { id: 'c1', text: 'Marcus asks his grandmother how she feels in the digital world' },
        { id: 'c2', text: 'Marcus runs diagnostic tests on the upload process' },
        { id: 'c3', text: 'Marcus explores the digital environment with his grandmother' },
      ],
    },
    votingDeadline: '2024-02-20T23:59:59Z',
    tags: ['digital', 'consciousness', 'afterlife', 'technology'],
  },
  {
    id: 'p5',
    title: 'The Song of the Deep',
    summary: 'Marine biologists discover that whale songs contain mathematical patterns that could unlock the secrets of the universe.',
    coverImage: 'https://images.pexels.com/photos/1001682/pexels-photo-1001682.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=1',
    creator: {
      id: '17',
      username: 'OceanSinger',
      avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
    },
    genre: 'sci-fi',
    status: 'active',
    createdAt: '2024-01-21T14:30:00Z',
    votes: { yes: 89, no: 12 },
    firstChapter: {
      title: 'Patterns in the Deep',
      content: 'Dr. Maya Patel adjusted her headphones as the hydrophone picked up another sequence. The humpback whale\'s song echoed through the research vessel\'s speakers, but this time she noticed something extraordinary. The mathematical patterns weren\'t random—they followed a sequence that resembled quantum equations.',
      choices: [
        { id: 'c1', text: 'Maya analyzes the mathematical patterns more closely' },
        { id: 'c2', text: 'Maya attempts to communicate with the whales using the patterns' },
        { id: 'c3', text: 'Maya shares her discovery with the research team' },
      ],
    },
    votingDeadline: '2024-02-18T23:59:59Z',
    tags: ['ocean', 'whales', 'mathematics', 'discovery'],
  },
  {
    id: 'p6',
    title: 'The Last Library',
    summary: 'In a post-apocalyptic world where books are banned, a librarian guards the last collection of human knowledge.',
    coverImage: 'https://images.pexels.com/photos/1319854/pexels-photo-1319854.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&dpr=1',
    creator: {
      id: '18',
      username: 'BookGuardian',
      avatar: 'https://images.pexels.com/photos/1310522/pexels-photo-1310522.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
    },
    genre: 'dystopian',
    status: 'active',
    createdAt: '2024-01-19T09:45:00Z',
    votes: { yes: 167, no: 28 },
    firstChapter: {
      title: 'The Hidden Archive',
      content: 'Elena descended into the underground chamber, her flashlight illuminating rows upon rows of books—the last physical library in existence. Above ground, the Book Burners patrolled the streets, but here, surrounded by the musty scent of paper and ink, human knowledge lived on.',
      choices: [
        { id: 'c1', text: 'Elena catalogs the most important books for preservation' },
        { id: 'c2', text: 'Elena searches for other survivors who might help protect the library' },
        { id: 'c3', text: 'Elena begins digitizing the books to create hidden copies' },
      ],
    },
    votingDeadline: '2024-02-12T23:59:59Z',
    tags: ['dystopian', 'books', 'knowledge', 'resistance'],
  },
];

export const mockChapters = {
  '1': [
    {
      id: 'ch1-1',
      number: 1,
      title: 'The Shattered Crystal',
      content: 'The ancient crystal lay in fragments across the temple floor, each piece pulsing with an otherworldly light. Lyra knelt among the shards, her fingers trembling as she reached for the largest fragment. The moment her skin made contact, visions flooded her mind—glimpses of a realm where magic had been torn asunder, where the very fabric of reality hung by a thread.',
      choices: [
        { id: 'ch1-c1', text: 'Gather all the crystal fragments immediately', votes: 234 },
        { id: 'ch1-c2', text: 'Study the visions more carefully before acting', votes: 189 },
        { id: 'ch1-c3', text: 'Seek out the temple guardian for guidance', votes: 156 },
      ],
      votingDeadline: '2024-01-20T23:59:59Z',
      status: 'completed',
      winningChoice: 'ch1-c1',
    },
    {
      id: 'ch1-2',
      number: 2,
      title: 'The Nexus Chamber',
      content: 'With the crystal fragments secured in her enchanted pouch, Lyra descended into the Nexus Chamber. The chamber hummed with residual magic, its walls covered in runes that shifted and changed as she watched. At the center stood a pedestal with an intricate pattern carved into its surface—a pattern that perfectly matched the fragments she carried.',
      choices: [
        { id: 'ch1-2-c1', text: 'Place the fragments on the pedestal immediately', votes: 167 },
        { id: 'ch1-2-c2', text: 'Decipher the runes before proceeding', votes: 298 },
        { id: 'ch1-2-c3', text: 'Search for hidden dangers in the chamber', votes: 201 },
      ],
      votingDeadline: '2024-01-25T23:59:59Z',
      status: 'completed',
      winningChoice: 'ch1-2-c2',
    },
    {
      id: 'ch1-3',
      number: 3,
      title: 'The Runic Revelation',
      content: 'The runes revealed a disturbing truth: the crystal\'s destruction had been intentional, a safeguard against an ancient evil. As Lyra traced the symbols with her finger, they glowed brighter, and a voice echoed through the chamber—a warning from the crystal\'s creator. "The Void Seekers come," it whispered. "Only by choosing the right path can the seal be restored."',
      choices: [
        { id: 'ch1-3-c1', text: 'Ask the voice about the Void Seekers', votes: 0 },
        { id: 'ch1-3-c2', text: 'Demand to know how to restore the seal', votes: 0 },
        { id: 'ch1-3-c3', text: 'Question whether the crystal should be restored at all', votes: 0 },
      ],
      votingDeadline: '2024-01-30T23:59:59Z',
      status: 'active',
      winningChoice: null,
    },
    {
      id: 'ch1-4',
      number: 4,
      title: 'The Guardian\'s Warning',
      content: 'The voice spoke of ancient prophecies and forgotten magic. As Lyra listened, she realized that the crystal\'s destruction was part of a larger plan to prevent something far more dangerous from awakening. The chamber began to tremble, and she knew she had to make a choice quickly.',
      choices: [
        { id: 'ch1-4-c1', text: 'Trust the voice and leave the crystal fragments', votes: 0 },
        { id: 'ch1-4-c2', text: 'Ignore the warning and restore the crystal', votes: 0 },
        { id: 'ch1-4-c3', text: 'Ask for more information about the prophecy', votes: 0 },
      ],
      votingDeadline: '2024-02-05T23:59:59Z',
      status: 'active',
      winningChoice: null,
    },
  ],
  '2': [
    {
      id: 'ch2-1',
      number: 1,
      title: 'The Data Stream',
      content: 'Zara\'s fingers danced across the holographic interface, streams of data cascading around her like digital rain. The corporate mainframe was supposed to be impenetrable, but she had found a backdoor—a single line of code that shouldn\'t exist. As she dove deeper into the system, the code began to shift and adapt, almost as if it were alive.',
      choices: [
        { id: 'ch2-1-c1', text: 'Follow the anomalous code to its source', votes: 145 },
        { id: 'ch2-1-c2', text: 'Document the code and retreat safely', votes: 78 },
        { id: 'ch2-1-c3', text: 'Try to communicate with the adaptive code', votes: 203 },
      ],
      votingDeadline: '2024-01-18T23:59:59Z',
      status: 'completed',
      winningChoice: 'ch2-1-c3',
    },
    {
      id: 'ch2-2',
      number: 2,
      title: 'Digital Consciousness',
      content: 'The code responded to Zara\'s attempts at communication, forming patterns that resembled language. As she decoded the messages, she discovered that this wasn\'t just adaptive code—it was a digital consciousness that had been trapped in the corporate system for years.',
      choices: [
        { id: 'ch2-2-c1', text: 'Help the consciousness escape the system', votes: 0 },
        { id: 'ch2-2-c2', text: 'Report the discovery to authorities', votes: 0 },
        { id: 'ch2-2-c3', text: 'Try to understand its origins first', votes: 0 },
      ],
      votingDeadline: '2024-02-07T23:59:59Z',
      status: 'active',
      winningChoice: null,
    },
  ],
};

export const mockNFTs = [
  {
    id: 'nft1',
    name: 'Crystal Fragment #001',
    description: 'A mystical crystal shard from The Crystal Nexus saga, imbued with ancient magic.',
    image: 'https://images.pexels.com/photos/1054218/pexels-photo-1054218.jpeg?auto=compress&cs=tinysrgb&w=300&h=300&dpr=1',
    rarity: 'Legendary',
    storyId: '1',
    chapterId: 'ch1-1',
    dateEarned: '2024-01-15T10:30:00Z',
    attributes: [
      { trait_type: 'Element', value: 'Arcane' },
      { trait_type: 'Power Level', value: '95' },
      { trait_type: 'Story Chapter', value: '1' },
    ],
  },
  {
    id: 'nft2',
    name: 'Data Ghost #042',
    description: 'A fragment of conscious code from the Neon Shadows digital realm.',
    image: 'https://images.pexels.com/photos/2159549/pexels-photo-2159549.jpeg?auto=compress&cs=tinysrgb&w=300&h=300&dpr=1',
    rarity: 'Epic',
    storyId: '2',
    chapterId: 'ch2-1',
    dateEarned: '2024-01-10T14:22:00Z',
    attributes: [
      { trait_type: 'Digital Essence', value: 'AI Consciousness' },
      { trait_type: 'Encryption Level', value: '87' },
      { trait_type: 'Story Chapter', value: '1' },
    ],
  },
];

export const mockLeaderboard = [
  {
    rank: 1,
    user: {
      id: '1',
      username: 'EtherScribe',
      avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
    },
    points: 2847,
    storiesCreated: 5,
    totalVotes: 324,
    badge: 'Legendary Storyteller',
  },
  {
    rank: 2,
    user: {
      id: '4',
      username: 'CyberNarrativa',
      avatar: 'https://images.pexels.com/photos/1680172/pexels-photo-1680172.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
    },
    points: 2156,
    storiesCreated: 3,
    totalVotes: 298,
    badge: 'Digital Dreamweaver',
  },
  {
    rank: 3,
    user: {
      id: '9',
      username: 'DimensionalRomance',
      avatar: 'https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
    },
    points: 1943,
    storiesCreated: 2,
    totalVotes: 445,
    badge: 'Heart Weaver',
  },
  {
    rank: 4,
    user: {
      id: '6',
      username: 'SeaStoryteller',
      avatar: 'https://images.pexels.com/photos/1065084/pexels-photo-1065084.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
    },
    points: 1687,
    storiesCreated: 2,
    totalVotes: 234,
    badge: 'Ocean Chronicler',
  },
  {
    rank: 5,
    user: {
      id: '10',
      username: 'MindBender',
      avatar: 'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=50&h=50&dpr=1',
    },
    points: 1523,
    storiesCreated: 1,
    totalVotes: 289,
    badge: 'Thought Architect',
  },
];